#
###################################
# Site wide configuration
####################################
#
title: RSFP
email:
description: Scott Longwell's webzone
url: http://slongwell.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          US/Pacific
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: RSFP
  avatar: longwell_photo.jpg
  job: "Scott Longwell"
  bio: ""
  email:
  disqus-shortname: "rsfp"
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: UA-73781724-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: slongwell #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
