remote_theme: pmarsceill/just-the-docs


title: rsfp
description: Scott Longwell's webzone
baseurl: "/just-the-docs" # the subpath of your site, e.g. /blog
url: "https://slongwell.github.io" # the base hostname & protocol for your site, e.g. http://example.com
